// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS7PSFlFu5d1By6rBK9LhBTgIAzmuwJuM',
    appId: '1:692455759980:web:abb9c84ea7970fc67ff849',
    messagingSenderId: '692455759980',
    projectId: 'study-ai-1c199',
    authDomain: 'study-ai-1c199.firebaseapp.com',
    storageBucket: 'study-ai-1c199.firebasestorage.app',
    measurementId: 'G-J6MJ507FSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEkqe0X0Wmu4l7aF7jjvkLd8yzs0XRZzk',
    appId: '1:692455759980:android:b37d2a4228a8f71a7ff849',
    messagingSenderId: '692455759980',
    projectId: 'study-ai-1c199',
    storageBucket: 'study-ai-1c199.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIon4RG5p_Jjjw-2-J1VCncjznliWFqUk',
    appId: '1:692455759980:ios:d1d460d71b4977ca7ff849',
    messagingSenderId: '692455759980',
    projectId: 'study-ai-1c199',
    storageBucket: 'study-ai-1c199.firebasestorage.app',
    iosBundleId: 'com.example.studyAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIon4RG5p_Jjjw-2-J1VCncjznliWFqUk',
    appId: '1:692455759980:ios:d1d460d71b4977ca7ff849',
    messagingSenderId: '692455759980',
    projectId: 'study-ai-1c199',
    storageBucket: 'study-ai-1c199.firebasestorage.app',
    iosBundleId: 'com.example.studyAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS7PSFlFu5d1By6rBK9LhBTgIAzmuwJuM',
    appId: '1:692455759980:web:32f732ca105588d57ff849',
    messagingSenderId: '692455759980',
    projectId: 'study-ai-1c199',
    authDomain: 'study-ai-1c199.firebaseapp.com',
    storageBucket: 'study-ai-1c199.firebasestorage.app',
    measurementId: 'G-4DM4B33ZKB',
  );
}
